
default_yaml: /workspace/jaeyoung/StoryTeller/ONE-PEACE/one_peace/run_scripts/finetune_3B.yaml

task:
  _name: image_text_retrieval
  data: /workspace/jaeyoung/StoryTeller/merged_caption_MMTTS.csv
  valid_data: /workspace/jaeyoung/StoryTeller/valid1000_merged_caption_MMTTS.csv
  # selected_cols: image_id,image,caption
  selected_cols: filename,caption1,caption2,caption3,caption4,caption5,emotion
  patch_image_size: 256
  valid_file: /workspace/jaeyoung/StoryTeller/valid1000_merged_caption_MMTTS.csv

criterion:
  _name: image_text_retrieval_criterion
  label_smoothing: 0.0

optimization:
  max_epoch: 5
  lr: [1.5e-4]
  update_freq: [1]
  skip_remainder_batch: false 

lr_scheduler:
  _name: adjust_cosine
  warmup_ratio: 0.1

dataset:
  batch_size: 8
  ensure_equal_batch: true

common:
  layer_decay: 0.9

checkpoint:
  best_checkpoint_metric: txt_r1
  save_dir: /workspace/jaeyoung/checkpoints/one_peace/mmtts_vl_0907

model:
  _name: one_peace_retrieval
  copy_rel_pos_table: true