
default_yaml: /workspace/jaeyoung/StoryTeller/ONE-PEACE/one_peace/run_scripts/finetune_3B.yaml

task:
  _name: audio_text_retrieval
  # data: /workspace/jaeyoung/StoryTeller/Updated_ESD_with_Captions.csv
  data: /workspace/jaeyoung/StoryTeller/merged_caption_imgpath_MMTTS.csv
  valid_data: /workspace/jaeyoung/StoryTeller/valid1000_merged_caption_imgpath_MMTTS.csv
  selected_cols: tmp_audiopath,caption1,caption2,caption3,caption4,caption5
  valid_file: /workspace/jaeyoung/StoryTeller/valid1000_merged_caption_imgpath_MMTTS.csv
  max_duration: 20
  head_type: al

criterion:
  _name: audio_text_retrieval_criterion
  label_smoothing: 0.0

optimization:
  max_epoch: 10
  lr: [1.5e-4]
  update_freq: [1]
  skip_remainder_batch: false

dataset:
  batch_size: 16
  ensure_equal_batch: true

common:
  layer_decay: 0.95

checkpoint:
  # restore_file: /workspace/jaeyoung/checkpoints/one_peace/mmtts_al_vl_0908/checkpoint_best.pt
  # restore_file: /workspace/jaeyoung/checkpoints/onepeace/one-peace_pretrained.pt
  restore_file: /workspace/jaeyoung/checkpoints/onepeace/esd_mmtts_al_1014/checkpoint_last.pt
  save_dir: /workspace/jaeyoung/checkpoints/onepeace/esd_mmtts_al_1014
  best_checkpoint_metric: txt_r1



model:
  _name: one_peace_retrieval
  copy_rel_pos_table: true
  encoder:
    drop_path_rate: 0.9